### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Shougo** [4513ECHO/zsh-sticky-shift#1]
```diff
diff --git a/README.md b/README.md
index b1db20f..b48c702 100644
--- a/README.md
+++ b/README.md
@@ -1,6 +1,6 @@
 # zsh-sticky-shift

-sticky shift for Zsh
+Sticky shift for Zsh

 ## How to Install

@@ -12,7 +12,7 @@ For example:
 zinit light 4513echo/zsh-sticky-shift
 ```

-2. Manualy install
+2. Manually install

 For example:

@@ -28,19 +28,19 @@ For example:

 ```sh
 export STICKY_SHIFT_KEY="@"
-export STIKY_DELAY=0.3
+export STICKY_DELAY=0.3
 ```

 * `STICKY_SHIFT_KEY`

 default: `;`

-* `STIKY_TABLE`
+* `STICKY_TABLE`

 default: `jis`

 `jis` or `us`

-* `STIKY_DELAY`
+* `STICKY_DELAY`
...skipping...
--- a/README.md
+++ b/README.md
@@ -1,6 +1,6 @@
 # zsh-sticky-shift

-sticky shift for Zsh
+Sticky shift for Zsh

 ## How to Install

@@ -12,7 +12,7 @@ For example:
 zinit light 4513echo/zsh-sticky-shift
 ```

-2. Manualy install
+2. Manually install

 For example:

@@ -28,19 +28,19 @@ For example:

 ```sh
 export STICKY_SHIFT_KEY="@"
-export STIKY_DELAY=0.3
+export STICKY_DELAY=0.3
 ```

 * `STICKY_SHIFT_KEY`

 default: `;`

-* `STIKY_TABLE`
+* `STICKY_TABLE`

 default: `jis`

 `jis` or `us`

-* `STIKY_DELAY`
+* `STICKY_DELAY`

 default: 1 (second)
```

**Comment by 4513ECHO** [comment]
Thank you.
